#!/usr/bin/env bash
# Install nginx web server
sudo apt-get update
sudo apt-get install -y nginx
sudo echo "Hello World" | sudo tee /var/www/html/index.nginx-debian.html
sudo sed -i "s/location \/ /location \/redirect_me /" /etc/nginx/sites-available/default
sudo sed -i "s/try_files \$uri \$uri\/ =404;/return 301 https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4\/home;/" /etc/nginx/sites-available/default
sudo service nginx start
