#!/usr/bin/env bash
# Install balancer to drive the traffic

sudo apt-get -y upgrade
sudo apt-get -y update
sudo apt-get -y install haproxy
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.default
echo "listen appname
        bind *:80
        mode http
        balance roundrobin
        server 4270-web-01 52.73.0.54:80 check
        server 4270-web-02 54.146.27.157:80 check" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy restart
