#!/usr/bin/env bash
#infinite loop
sudo touch /var/run/holbertonscript.pid
sudo chmod 777 /var/run/holbertonscript.pid
echo $$ > /var/run/holbertonscript.pid
while true
do
        echo To infinity and beyond
        sleep 2
	trap 'echo "I hate the kill command"; sudo rm /var/run/myscript.pid; exit' SIGTERM
	trap 'echo "Y U no love me?!"' SIGINT
	trap 'sudo rm /var/run/myscript.pid; exit' SIGQUIT
done
