#!/usr/bin/env bash
# good and bad luck
i=0
while [ $i -lt 10 ];
do
        echo Best School
        ((i++))
        if [ $i -eq 4 ];
        then
        echo bad luck
elif [ $i -eq 8 ];
then
	echo good luck
        fi
done
